# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Set environment variables for the S3 API
ENV S3_API_ENDPOINT=https://s3-eu-west-1.amazonaws.com
ENV S3_ACCESS_KEY=your-s3-access-key
ENV S3_SECRET_KEY=your-s3-secret-key
ENV S3_BUCKET_NAME=static-site-bucket-curvetech

# Expose the port on which the frontend will run
EXPOSE 3000

# Command to start the application
CMD [ "npm", "start" ]


